CMT_FILES = {'code/cmt/src/affinepreconditioner.cpp', ...
             'code/cmt/src/affinetransform.cpp', ...
             'code/cmt/src/binningtransform.cpp', ...
             'code/cmt/src/conditionaldistribution.cpp', ...
             'code/cmt/src/distribution.cpp', ...
             'code/cmt/src/gsm.cpp', ...
             'code/cmt/src/glm.cpp', ...
             'code/cmt/src/mcgsm.cpp', ...
             'code/cmt/src/mcbm.cpp', ...
             'code/cmt/src/mixture.cpp', ...
             'code/cmt/src/mlr.cpp', ...
             'code/cmt/src/nonlinearities.cpp', ...
             'code/cmt/src/patchmodel.cpp', ...
             'code/cmt/src/pcapreconditioner.cpp', ...
             'code/cmt/src/pcatransform.cpp', ...
             'code/cmt/src/preconditioner.cpp', ...
             'code/cmt/src/stm.cpp', ...
             'code/cmt/src/tools.cpp', ...
             'code/cmt/src/trainable.cpp', ...
             'code/cmt/src/utils.cpp', ...
             'code/cmt/src/univariatedistributions.cpp', ...
             'code/cmt/src/whiteningpreconditioner.cpp', ...
             'code/cmt/src/whiteningtransform.cpp'};      

TRAINABLE = { 'code/cmt/matlab/src/conditionaldistributioninterface.cpp', ...
              'code/cmt/matlab/src/trainableinterface.cpp'};
                    
INCLUDES = {'-Icode/cmt/include/', '-Icode/cmt/matlab/include/', '-Icode/', '-Icode/liblbfgs/include'};
LIBS     = {'-Lcode/liblbfgs/lib/.libs/', '-llbfgs'};
OPTIONS  = {'-outdir', 'code/cmt/matlab/+cmt', '-largeArrayDims', 'CXXFLAGS=""\$CXXFLAGS -std=c++0x""'}; 


mex('-v', OPTIONS{:}, INCLUDES{:}, LIBS{:}, 'code/cmt/matlab/src/glminterface.cpp', TRAINABLE{:}, CMT_FILES{:})

mex('-v', OPTIONS{:}, INCLUDES{:}, LIBS{:}, 'code/cmt/matlab/src/stminterface.cpp', TRAINABLE{:}, CMT_FILES{:})